---
name: CI/CD
on:
  push:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger]

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  lint:
    uses: jmpa-io/pipelines/.github/workflows/10-lint.yml@main
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_RUNNER_ROLE_NAME: ${{ secrets.AWS_RUNNER_ROLE_NAME }}
      ADMIN_GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}

  deploy:
    needs: [lint]
    uses: jmpa-io/pipelines/.github/workflows/40-deploy-to-aws.yml@main
    with:
      environment: prod
      templates: deploy
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_RUNNER_ROLE_NAME: ${{ secrets.AWS_RUNNER_ROLE_NAME }}

  build-website:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout.
        uses: actions/checkout@v4

      - name: Upload artifact.
        uses: actions/upload-artifact@v4
        with:
          name: startpage.jcleal.me
          path: src/*
          if-no-files-found: error
          retention-days: 7

  upload-website:
    needs: [deploy, build-website]
    uses: jmpa-io/pipelines/.github/workflows/50-upload-artifacts-to-s3.yml@main
    with:
      artifact: startpage.jcleal.me
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_RUNNER_ROLE_NAME: ${{ secrets.AWS_RUNNER_ROLE_NAME }}

  post-to-slack:
    needs: [lint, deploy, build-website, upload-website]
    if: always()
    uses: jmpa-io/pipelines/.github/workflows/99-post-to-slack.yml@main
    secrets:
      WEBHOOK: ${{ secrets.SLACK_GITHUB_NOTIFICATIONS_WEBHOOK }}
